require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-performance
  - rubocop-factory_bot
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/ExampleLength:
  Enabled: False

RSpec/MultipleExpectations:
  Enabled: False

RSpec/PredicateMatcher:
  Enabled: False